# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fcc77f8a9ea2079423768ab42d470ec8a1604e614830719505a97ca15ab399c13d122b0b428445bbaa3b59fee708392121fb1150b5e71e662a77eecd1f8fee9

test:
  secret_key_base: 3995ee2dc3ec1d569d06ed60b27aa2866cbd1233d7a6f0b2829bd5d08e374679d8891d30142fbafa2eb0ce53e281a09538ecd10d153e7f3789007e67cab3109e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
